Fix to compile in project using C++98
When filesystem/path.h is used in a project with C++98, the gcc issues the following errors:

1) filesystem/path.h:243:16: error: ‘remove’ is not a member of ‘std’
         return std::remove(str().c_str()) == 0;

In C++98, std::remove is defined in stdio.h, added #include <cstdio> to path.h

2) rvalue references are not supported in C++98. Protected move-constructor and operator= with #if __cplusplus >= 201103L