Fix compile on cygwin
1) The compile with gcc 5.4.0 on cygwin 2.6.0 fails with:

filesystem/path.h:81:41: error: ‘realpath’ was not declared in this scope
         if (realpath(str().c_str(), temp) == NULL)

gcc -std=c++11 compiles a strict-ANSI dialect of C++, where realpath is not declared
- see https://gcc.gnu.org/onlinedocs/gcc/C-Dialect-Options.html

Some header files protect non-ANSI function declarations with #ifndef __STRICT_ANSI__.

To compile this module , one needs either to use the GNU dialect of C++:
    -std=gnu++11
or undefine the strict ANSI macro:
    -std=c++11 -U__STRICT_ANSI__

The second option was chosen.

2) The compile with gcc 5.4.0 on cygwin 2.6.0 fails with:

filesystem/path.h:80:19: error: ‘PATH_MAX’ was not declared in this scope
         char temp[PATH_MAX];

PATH_MAX is defined in cygwin in limits.h, requiring #include <climits> in path.h